### PR TITLE
Own the `fit` and `predict` functions

### LINKED ISSUE #1: Replace StatsBase with our own `Models.fit` and `Models.predict`
StatsBase is a large and unnecessaary dependency. Users should not need to depend on anything but this package itself. I propose we just define our own `fit` and `predict`, which is extended by packages implementing the interface.

### PR DESCRIPTION
**Pull request by nickrobinson251**
closes #1

### CODE REVIEW

**Comment by oxinabox** [comment]
I am just not sure.
This change is definately breaking.

Packages exporting the Models.jl interface but using the StatsBase "interface" internally will become more complex as they will use both `fit` functions often.

**Comment by glennmoy** [comment]
Apart from fitting to some `RegressionModel` types - there is no particular overlap that I can see that warrants overload `StatsBase.fit`, `StatsBase.predict`. Unless `RegressionModel` subtypes `Model` in the future there shouldn't be any clashes as of now I don't think?

**Comment by oxinabox** [comment]
There are loads of clashes, with Lasso for example.
But maybe those are not to bad.

**Comment by nickrobinson251** [comment]
I think my gripe is that StatBase has a bunch of API stuff (like the names `fit` and `predict`) but also a _ton_ of functionality (it's "*Base" name is a misnomer). So alternative is to move `fit`, `predict` somewhere else... but that's a whole other kettle of fish 🐟

**Pull request closed without merging**
